JOGOS = [
    # ── Fase de Grupos — 1ª Rodada ────────────────────────────────────────────
    {
        "id": 1,
        "data": "11/06",
        "dia": "Qui",
        "hora": "16h",
        "grupo": "A",
        "time1": "México",
        "flag1": "🇲🇽",
        "time2": "África do Sul",
        "flag2": "🇿🇦",
        "local": "Cidade do México",
        "fase": "Grupos",
    },
    {
        "id": 2,
        "data": "11/06",
        "dia": "Qui",
        "hora": "23h",
        "grupo": "A",
        "time1": "Coreia do Sul",
        "flag1": "🇰🇷",
        "time2": "República Tcheca",
        "flag2": "🇨🇿",
        "local": "Guadalajara",
        "fase": "Grupos",
    },
    {
        "id": 3,
        "data": "12/06",
        "dia": "Sex",
        "hora": "16h",
        "grupo": "B",
        "time1": "Canadá",
        "flag1": "🇨🇦",
        "time2": "Bósnia e Herzegovina",
        "flag2": "🇧🇦",
        "local": "Toronto",
        "fase": "Grupos",
    },
    {
        "id": 4,
        "data": "12/06",
        "dia": "Sex",
        "hora": "22h",
        "grupo": "D",
        "time1": "Estados Unidos",
        "flag1": "🇺🇸",
        "time2": "Paraguai",
        "flag2": "🇵🇾",
        "local": "Los Angeles",
        "fase": "Grupos",
    },
    {
        "id": 5,
        "data": "14/06",
        "dia": "Dom",
        "hora": "01h",
        "grupo": "D",
        "time1": "Austrália",
        "flag1": "🇦🇺",
        "time2": "Turquia",
        "flag2": "🇹🇷",
        "local": "Vancouver",
        "fase": "Grupos",
    },
    {
        "id": 6,
        "data": "13/06",
        "dia": "Sáb",
        "hora": "16h",
        "grupo": "B",
        "time1": "Catar",
        "flag1": "🇶🇦",
        "time2": "Suíça",
        "flag2": "🇨🇭",
        "local": "San Francisco",
        "fase": "Grupos",
    },
    {
        "id": 7,
        "data": "13/06",
        "dia": "Sáb",
        "hora": "19h",
        "grupo": "C",
        "time1": "Brasil",
        "flag1": "🇧🇷",
        "time2": "Marrocos",
        "flag2": "🇲🇦",
        "local": "Nova York/NJ",
        "fase": "Grupos",
    },
    {
        "id": 8,
        "data": "13/06",
        "dia": "Sáb",
        "hora": "22h",
        "grupo": "C",
        "time1": "Haiti",
        "flag1": "🇭🇹",
        "time2": "Escócia",
        "flag2": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "local": "Boston",
        "fase": "Grupos",
    },
    {
        "id": 9,
        "data": "14/06",
        "dia": "Dom",
        "hora": "14h",
        "grupo": "E",
        "time1": "Alemanha",
        "flag1": "🇩🇪",
        "time2": "Curaçao",
        "flag2": "🇨🇼",
        "local": "Houston",
        "fase": "Grupos",
    },
    {
        "id": 10,
        "data": "14/06",
        "dia": "Dom",
        "hora": "17h",
        "grupo": "F",
        "time1": "Holanda",
        "flag1": "🇳🇱",
        "time2": "Japão",
        "flag2": "🇯🇵",
        "local": "Dallas",
        "fase": "Grupos",
    },
    {
        "id": 11,
        "data": "14/06",
        "dia": "Dom",
        "hora": "20h",
        "grupo": "E",
        "time1": "Costa do Marfim",
        "flag1": "🇨🇮",
        "time2": "Equador",
        "flag2": "🇪🇨",
        "local": "Filadélfia",
        "fase": "Grupos",
    },
    {
        "id": 12,
        "data": "14/06",
        "dia": "Dom",
        "hora": "23h",
        "grupo": "F",
        "time1": "Suécia",
        "flag1": "🇸🇪",
        "time2": "Tunísia",
        "flag2": "🇹🇳",
        "local": "Monterrey",
        "fase": "Grupos",
    },
    {
        "id": 13,
        "data": "15/06",
        "dia": "Seg",
        "hora": "13h",
        "grupo": "H",
        "time1": "Espanha",
        "flag1": "🇪🇸",
        "time2": "Cabo Verde",
        "flag2": "🇨🇻",
        "local": "Atlanta",
        "fase": "Grupos",
    },
    {
        "id": 14,
        "data": "15/06",
        "dia": "Seg",
        "hora": "16h",
        "grupo": "G",
        "time1": "Bélgica",
        "flag1": "🇧🇪",
        "time2": "Egito",
        "flag2": "🇪🇬",
        "local": "Seattle",
        "fase": "Grupos",
    },
    {
        "id": 15,
        "data": "15/06",
        "dia": "Seg",
        "hora": "19h",
        "grupo": "H",
        "time1": "Arábia Saudita",
        "flag1": "🇸🇦",
        "time2": "Uruguai",
        "flag2": "🇺🇾",
        "local": "Miami",
        "fase": "Grupos",
    },
    {
        "id": 16,
        "data": "15/06",
        "dia": "Seg",
        "hora": "22h",
        "grupo": "G",
        "time1": "Irã",
        "flag1": "🇮🇷",
        "time2": "Nova Zelândia",
        "flag2": "🇳🇿",
        "local": "Los Angeles",
        "fase": "Grupos",
    },
    {
        "id": 17,
        "data": "16/06",
        "dia": "Ter",
        "hora": "22h",
        "grupo": "J",
        "time1": "Argentina",
        "flag1": "🇦🇷",
        "time2": "Argélia",
        "flag2": "🇩🇿",
        "local": "Kansas City",
        "fase": "Grupos",
    },
    {
        "id": 18,
        "data": "16/06",
        "dia": "Ter",
        "hora": "16h",
        "grupo": "I",
        "time1": "França",
        "flag1": "🇫🇷",
        "time2": "Senegal",
        "flag2": "🇸🇳",
        "local": "Nova York/NJ",
        "fase": "Grupos",
    },
    {
        "id": 19,
        "data": "16/06",
        "dia": "Ter",
        "hora": "19h",
        "grupo": "I",
        "time1": "Iraque",
        "flag1": "🇮🇶",
        "time2": "Noruega",
        "flag2": "🇳🇴",
        "local": "Boston",
        "fase": "Grupos",
    },
    {
        "id": 20,
        "data": "17/06",
        "dia": "Qua",
        "hora": "01h",
        "grupo": "J",
        "time1": "Áustria",
        "flag1": "🇦🇹",
        "time2": "Jordânia",
        "flag2": "🇯🇴",
        "local": "San Francisco",
        "fase": "Grupos",
    },
    {
        "id": 21,
        "data": "17/06",
        "dia": "Qua",
        "hora": "14h",
        "grupo": "K",
        "time1": "Portugal",
        "flag1": "🇵🇹",
        "time2": "RD Congo",
        "flag2": "🇨🇩",
        "local": "Houston",
        "fase": "Grupos",
    },
    {
        "id": 22,
        "data": "17/06",
        "dia": "Qua",
        "hora": "17h",
        "grupo": "L",
        "time1": "Inglaterra",
        "flag1": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "time2": "Croácia",
        "flag2": "🇭🇷",
        "local": "Dallas",
        "fase": "Grupos",
    },
    {
        "id": 23,
        "data": "17/06",
        "dia": "Qua",
        "hora": "20h",
        "grupo": "L",
        "time1": "Gana",
        "flag1": "🇬🇭",
        "time2": "Panamá",
        "flag2": "🇵🇦",
        "local": "Toronto",
        "fase": "Grupos",
    },
    {
        "id": 24,
        "data": "17/06",
        "dia": "Qua",
        "hora": "23h",
        "grupo": "K",
        "time1": "Uzbequistão",
        "flag1": "🇺🇿",
        "time2": "Colômbia",
        "flag2": "🇨🇴",
        "local": "Cidade do México",
        "fase": "Grupos",
    },
    # ── Fase de Grupos — 2ª Rodada ────────────────────────────────────────────
    {
        "id": 25,
        "data": "18/06",
        "dia": "Qui",
        "hora": "13h",
        "grupo": "A",
        "time1": "República Tcheca",
        "flag1": "🇨🇿",
        "time2": "África do Sul",
        "flag2": "🇿🇦",
        "local": "Atlanta",
        "fase": "Grupos",
    },
    {
        "id": 26,
        "data": "18/06",
        "dia": "Qui",
        "hora": "16h",
        "grupo": "B",
        "time1": "Suíça",
        "flag1": "🇨🇭",
        "time2": "Bósnia e Herzegovina",
        "flag2": "🇧🇦",
        "local": "Los Angeles",
        "fase": "Grupos",
    },
    {
        "id": 27,
        "data": "18/06",
        "dia": "Qui",
        "hora": "19h",
        "grupo": "B",
        "time1": "Canadá",
        "flag1": "🇨🇦",
        "time2": "Catar",
        "flag2": "🇶🇦",
        "local": "Vancouver",
        "fase": "Grupos",
    },
    {
        "id": 28,
        "data": "18/06",
        "dia": "Qui",
        "hora": "22h",
        "grupo": "A",
        "time1": "México",
        "flag1": "🇲🇽",
        "time2": "Coreia do Sul",
        "flag2": "🇰🇷",
        "local": "Guadalajara",
        "fase": "Grupos",
    },
    {
        "id": 29,
        "data": "20/06",
        "dia": "Sáb",
        "hora": "01h",
        "grupo": "D",
        "time1": "Turquia",
        "flag1": "🇹🇷",
        "time2": "Paraguai",
        "flag2": "🇵🇾",
        "local": "San Francisco",
        "fase": "Grupos",
    },
    {
        "id": 30,
        "data": "19/06",
        "dia": "Sex",
        "hora": "16h",
        "grupo": "D",
        "time1": "Estados Unidos",
        "flag1": "🇺🇸",
        "time2": "Austrália",
        "flag2": "🇦🇺",
        "local": "Seattle",
        "fase": "Grupos",
    },
    {
        "id": 31,
        "data": "19/06",
        "dia": "Sex",
        "hora": "19h",
        "grupo": "C",
        "time1": "Escócia",
        "flag1": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "time2": "Marrocos",
        "flag2": "🇲🇦",
        "local": "Boston",
        "fase": "Grupos",
    },
    {
        "id": 32,
        "data": "19/06",
        "dia": "Sex",
        "hora": "22h",
        "grupo": "C",
        "time1": "Brasil",
        "flag1": "🇧🇷",
        "time2": "Haiti",
        "flag2": "🇭🇹",
        "local": "Filadélfia",
        "fase": "Grupos",
    },
    {
        "id": 33,
        "data": "20/06",
        "dia": "Sáb",
        "hora": "14h",
        "grupo": "F",
        "time1": "Holanda",
        "flag1": "🇳🇱",
        "time2": "Suécia",
        "flag2": "🇸🇪",
        "local": "Houston",
        "fase": "Grupos",
    },
    {
        "id": 34,
        "data": "20/06",
        "dia": "Sáb",
        "hora": "17h",
        "grupo": "E",
        "time1": "Alemanha",
        "flag1": "🇩🇪",
        "time2": "Costa do Marfim",
        "flag2": "🇨🇮",
        "local": "Toronto",
        "fase": "Grupos",
    },
    {
        "id": 35,
        "data": "20/06",
        "dia": "Sáb",
        "hora": "21h",
        "grupo": "E",
        "time1": "Equador",
        "flag1": "🇪🇨",
        "time2": "Curaçao",
        "flag2": "🇨🇼",
        "local": "Kansas City",
        "fase": "Grupos",
    },
    {
        "id": 36,
        "data": "21/06",
        "dia": "Dom",
        "hora": "01h",
        "grupo": "F",
        "time1": "Tunísia",
        "flag1": "🇹🇳",
        "time2": "Japão",
        "flag2": "🇯🇵",
        "local": "Monterrey",
        "fase": "Grupos",
    },
    {
        "id": 37,
        "data": "21/06",
        "dia": "Dom",
        "hora": "13h",
        "grupo": "H",
        "time1": "Espanha",
        "flag1": "🇪🇸",
        "time2": "Arábia Saudita",
        "flag2": "🇸🇦",
        "local": "Atlanta",
        "fase": "Grupos",
    },
    {
        "id": 38,
        "data": "21/06",
        "dia": "Dom",
        "hora": "16h",
        "grupo": "G",
        "time1": "Bélgica",
        "flag1": "🇧🇪",
        "time2": "Irã",
        "flag2": "🇮🇷",
        "local": "Los Angeles",
        "fase": "Grupos",
    },
    {
        "id": 39,
        "data": "21/06",
        "dia": "Dom",
        "hora": "19h",
        "grupo": "H",
        "time1": "Uruguai",
        "flag1": "🇺🇾",
        "time2": "Cabo Verde",
        "flag2": "🇨🇻",
        "local": "Miami",
        "fase": "Grupos",
    },
    {
        "id": 40,
        "data": "21/06",
        "dia": "Dom",
        "hora": "22h",
        "grupo": "G",
        "time1": "Nova Zelândia",
        "flag1": "🇳🇿",
        "time2": "Egito",
        "flag2": "🇪🇬",
        "local": "Vancouver",
        "fase": "Grupos",
    },
    {
        "id": 41,
        "data": "22/06",
        "dia": "Seg",
        "hora": "14h",
        "grupo": "J",
        "time1": "Argentina",
        "flag1": "🇦🇷",
        "time2": "Áustria",
        "flag2": "🇦🇹",
        "local": "Dallas",
        "fase": "Grupos",
    },
    {
        "id": 42,
        "data": "22/06",
        "dia": "Seg",
        "hora": "18h",
        "grupo": "I",
        "time1": "França",
        "flag1": "🇫🇷",
        "time2": "Iraque",
        "flag2": "🇮🇶",
        "local": "Filadélfia",
        "fase": "Grupos",
    },
    {
        "id": 43,
        "data": "22/06",
        "dia": "Seg",
        "hora": "21h",
        "grupo": "I",
        "time1": "Noruega",
        "flag1": "🇳🇴",
        "time2": "Senegal",
        "flag2": "🇸🇳",
        "local": "Nova York/NJ",
        "fase": "Grupos",
    },
    {
        "id": 44,
        "data": "23/06",
        "dia": "Ter",
        "hora": "00h",
        "grupo": "J",
        "time1": "Jordânia",
        "flag1": "🇯🇴",
        "time2": "Argélia",
        "flag2": "🇩🇿",
        "local": "San Francisco",
        "fase": "Grupos",
    },
    {
        "id": 45,
        "data": "23/06",
        "dia": "Ter",
        "hora": "14h",
        "grupo": "K",
        "time1": "Portugal",
        "flag1": "🇵🇹",
        "time2": "Uzbequistão",
        "flag2": "🇺🇿",
        "local": "Houston",
        "fase": "Grupos",
    },
    {
        "id": 46,
        "data": "23/06",
        "dia": "Ter",
        "hora": "17h",
        "grupo": "L",
        "time1": "Inglaterra",
        "flag1": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "time2": "Gana",
        "flag2": "🇬🇭",
        "local": "Boston",
        "fase": "Grupos",
    },
    {
        "id": 47,
        "data": "23/06",
        "dia": "Ter",
        "hora": "20h",
        "grupo": "L",
        "time1": "Panamá",
        "flag1": "🇵🇦",
        "time2": "Croácia",
        "flag2": "🇭🇷",
        "local": "Toronto",
        "fase": "Grupos",
    },
    {
        "id": 48,
        "data": "23/06",
        "dia": "Ter",
        "hora": "23h",
        "grupo": "K",
        "time1": "Colômbia",
        "flag1": "🇨🇴",
        "time2": "RD Congo",
        "flag2": "🇨🇩",
        "local": "Guadalajara",
        "fase": "Grupos",
    },
    # ── Fase de Grupos — 3ª Rodada ────────────────────────────────────────────
    {
        "id": 49,
        "data": "24/06",
        "dia": "Qua",
        "hora": "16h",
        "grupo": "B",
        "time1": "Suíça",
        "flag1": "🇨🇭",
        "time2": "Canadá",
        "flag2": "🇨🇦",
        "local": "Vancouver",
        "fase": "Grupos",
    },
    {
        "id": 50,
        "data": "24/06",
        "dia": "Qua",
        "hora": "16h",
        "grupo": "B",
        "time1": "Bósnia e Herzegovina",
        "flag1": "🇧🇦",
        "time2": "Catar",
        "flag2": "🇶🇦",
        "local": "Seattle",
        "fase": "Grupos",
    },
    {
        "id": 51,
        "data": "24/06",
        "dia": "Qua",
        "hora": "19h",
        "grupo": "C",
        "time1": "Escócia",
        "flag1": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "time2": "Brasil",
        "flag2": "🇧🇷",
        "local": "Miami",
        "fase": "Grupos",
    },
    {
        "id": 52,
        "data": "24/06",
        "dia": "Qua",
        "hora": "19h",
        "grupo": "C",
        "time1": "Marrocos",
        "flag1": "🇲🇦",
        "time2": "Haiti",
        "flag2": "🇭🇹",
        "local": "Atlanta",
        "fase": "Grupos",
    },
    {
        "id": 53,
        "data": "24/06",
        "dia": "Qua",
        "hora": "22h",
        "grupo": "A",
        "time1": "República Tcheca",
        "flag1": "🇨🇿",
        "time2": "México",
        "flag2": "🇲🇽",
        "local": "Cidade do México",
        "fase": "Grupos",
    },
    {
        "id": 54,
        "data": "24/06",
        "dia": "Qua",
        "hora": "22h",
        "grupo": "A",
        "time1": "África do Sul",
        "flag1": "🇿🇦",
        "time2": "Coreia do Sul",
        "flag2": "🇰🇷",
        "local": "Monterrey",
        "fase": "Grupos",
    },
    {
        "id": 55,
        "data": "25/06",
        "dia": "Qui",
        "hora": "17h",
        "grupo": "E",
        "time1": "Equador",
        "flag1": "🇪🇨",
        "time2": "Alemanha",
        "flag2": "🇩🇪",
        "local": "Nova York/NJ",
        "fase": "Grupos",
    },
    {
        "id": 56,
        "data": "25/06",
        "dia": "Qui",
        "hora": "17h",
        "grupo": "E",
        "time1": "Curaçao",
        "flag1": "🇨🇼",
        "time2": "Costa do Marfim",
        "flag2": "🇨🇮",
        "local": "Filadélfia",
        "fase": "Grupos",
    },
    {
        "id": 57,
        "data": "25/06",
        "dia": "Qui",
        "hora": "20h",
        "grupo": "F",
        "time1": "Japão",
        "flag1": "🇯🇵",
        "time2": "Suécia",
        "flag2": "🇸🇪",
        "local": "Dallas",
        "fase": "Grupos",
    },
    {
        "id": 58,
        "data": "25/06",
        "dia": "Qui",
        "hora": "20h",
        "grupo": "F",
        "time1": "Tunísia",
        "flag1": "🇹🇳",
        "time2": "Holanda",
        "flag2": "🇳🇱",
        "local": "Kansas City",
        "fase": "Grupos",
    },
    {
        "id": 59,
        "data": "25/06",
        "dia": "Qui",
        "hora": "23h",
        "grupo": "D",
        "time1": "Turquia",
        "flag1": "🇹🇷",
        "time2": "Estados Unidos",
        "flag2": "🇺🇸",
        "local": "Los Angeles",
        "fase": "Grupos",
    },
    {
        "id": 60,
        "data": "25/06",
        "dia": "Qui",
        "hora": "23h",
        "grupo": "D",
        "time1": "Paraguai",
        "flag1": "🇵🇾",
        "time2": "Austrália",
        "flag2": "🇦🇺",
        "local": "San Francisco",
        "fase": "Grupos",
    },
    {
        "id": 61,
        "data": "26/06",
        "dia": "Sex",
        "hora": "16h",
        "grupo": "I",
        "time1": "Noruega",
        "flag1": "🇳🇴",
        "time2": "França",
        "flag2": "🇫🇷",
        "local": "Boston",
        "fase": "Grupos",
    },
    {
        "id": 62,
        "data": "26/06",
        "dia": "Sex",
        "hora": "16h",
        "grupo": "I",
        "time1": "Senegal",
        "flag1": "🇸🇳",
        "time2": "Iraque",
        "flag2": "🇮🇶",
        "local": "Toronto",
        "fase": "Grupos",
    },
    {
        "id": 63,
        "data": "26/06",
        "dia": "Sex",
        "hora": "21h",
        "grupo": "H",
        "time1": "Cabo Verde",
        "flag1": "🇨🇻",
        "time2": "Arábia Saudita",
        "flag2": "🇸🇦",
        "local": "Houston",
        "fase": "Grupos",
    },
    {
        "id": 64,
        "data": "26/06",
        "dia": "Sex",
        "hora": "21h",
        "grupo": "H",
        "time1": "Uruguai",
        "flag1": "🇺🇾",
        "time2": "Espanha",
        "flag2": "🇪🇸",
        "local": "Guadalajara",
        "fase": "Grupos",
    },
    {
        "id": 65,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "00h",
        "grupo": "G",
        "time1": "Egito",
        "flag1": "🇪🇬",
        "time2": "Irã",
        "flag2": "🇮🇷",
        "local": "Seattle",
        "fase": "Grupos",
    },
    {
        "id": 66,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "00h",
        "grupo": "G",
        "time1": "Nova Zelândia",
        "flag1": "🇳🇿",
        "time2": "Bélgica",
        "flag2": "🇧🇪",
        "local": "Vancouver",
        "fase": "Grupos",
    },
    {
        "id": 67,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "18h",
        "grupo": "L",
        "time1": "Panamá",
        "flag1": "🇵🇦",
        "time2": "Inglaterra",
        "flag2": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "local": "Nova York/NJ",
        "fase": "Grupos",
    },
    {
        "id": 68,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "18h",
        "grupo": "L",
        "time1": "Croácia",
        "flag1": "🇭🇷",
        "time2": "Gana",
        "flag2": "🇬🇭",
        "local": "Filadélfia",
        "fase": "Grupos",
    },
    {
        "id": 69,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "20h30",
        "grupo": "K",
        "time1": "Colômbia",
        "flag1": "🇨🇴",
        "time2": "Portugal",
        "flag2": "🇵🇹",
        "local": "Miami",
        "fase": "Grupos",
    },
    {
        "id": 70,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "20h30",
        "grupo": "K",
        "time1": "RD Congo",
        "flag1": "🇨🇩",
        "time2": "Uzbequistão",
        "flag2": "🇺🇿",
        "local": "Atlanta",
        "fase": "Grupos",
    },
    {
        "id": 71,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "23h",
        "grupo": "J",
        "time1": "Argélia",
        "flag1": "🇩🇿",
        "time2": "Áustria",
        "flag2": "🇦🇹",
        "local": "Kansas City",
        "fase": "Grupos",
    },
    {
        "id": 72,
        "data": "27/06",
        "dia": "Sáb",
        "hora": "23h",
        "grupo": "J",
        "time1": "Jordânia",
        "flag1": "🇯🇴",
        "time2": "Argentina",
        "flag2": "🇦🇷",
        "local": "Dallas",
        "fase": "Grupos",
    },
    # ── Mata-mata ─────────────────────────────────────────────────────────────
    {
        "id": 73,
        "data": "28/06",
        "dia": "Dom",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 74,
        "data": "29/06",
        "dia": "Seg",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 75,
        "data": "30/06",
        "dia": "Ter",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 76,
        "data": "01/07",
        "dia": "Qua",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 77,
        "data": "02/07",
        "dia": "Qui",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 78,
        "data": "03/07",
        "dia": "Sex",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "32avos",
    },
    {
        "id": 79,
        "data": "04/07",
        "dia": "Sáb",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "Oitavas",
    },
    {
        "id": 80,
        "data": "05/07",
        "dia": "Dom",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "Oitavas",
    },
    {
        "id": 81,
        "data": "06/07",
        "dia": "Seg",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "Oitavas",
    },
    {
        "id": 82,
        "data": "07/07",
        "dia": "Ter",
        "hora": "?",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "A definir",
        "fase": "Oitavas",
    },
    {
        "id": 83,
        "data": "09/07",
        "dia": "Qui",
        "hora": "17h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Boston",
        "fase": "Quartas",
    },
    {
        "id": 84,
        "data": "10/07",
        "dia": "Sex",
        "hora": "16h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Los Angeles",
        "fase": "Quartas",
    },
    {
        "id": 85,
        "data": "11/07",
        "dia": "Sáb",
        "hora": "18h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Miami",
        "fase": "Quartas",
    },
    {
        "id": 86,
        "data": "11/07",
        "dia": "Sáb",
        "hora": "21h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Kansas City",
        "fase": "Quartas",
    },
    {
        "id": 87,
        "data": "14/07",
        "dia": "Ter",
        "hora": "16h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Dallas",
        "fase": "Semifinal",
    },
    {
        "id": 88,
        "data": "15/07",
        "dia": "Qua",
        "hora": "16h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Atlanta",
        "fase": "Semifinal",
    },
    {
        "id": 89,
        "data": "18/07",
        "dia": "Sáb",
        "hora": "18h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Miami",
        "fase": "3º Lugar",
    },
    {
        "id": 90,
        "data": "19/07",
        "dia": "Dom",
        "hora": "16h",
        "grupo": "",
        "time1": "A definir",
        "flag1": "🏳",
        "time2": "A definir",
        "flag2": "🏳",
        "local": "Nova York/NJ",
        "fase": "Final",
    },
]

# Mapeamento de nomes da API (inglês) → nomes locais (português)
MAPA_NOMES = {
    "Brazil": "Brasil",
    "Mexico": "México",
    "United States": "Estados Unidos",
    "South Africa": "África do Sul",
    "South Korea": "Coreia do Sul",
    "Canada": "Canadá",
    "Australia": "Austrália",
    "Qatar": "Catar",
    "Switzerland": "Suíça",
    "Morocco": "Marrocos",
    "Haiti": "Haiti",
    "Scotland": "Escócia",
    "Germany": "Alemanha",
    "Netherlands": "Holanda",
    "Japan": "Japão",
    "Ivory Coast": "Costa do Marfim",
    "Côte d'Ivoire": "Costa do Marfim",
    "Ecuador": "Equador",
    "Tunisia": "Tunísia",
    "Spain": "Espanha",
    "Cape Verde": "Cabo Verde",
    "Belgium": "Bélgica",
    "Egypt": "Egito",
    "Saudi Arabia": "Arábia Saudita",
    "Uruguay": "Uruguai",
    "Iran": "Irã",
    "New Zealand": "Nova Zelândia",
    "Argentina": "Argentina",
    "Algeria": "Argélia",
    "France": "França",
    "Senegal": "Senegal",
    "Norway": "Noruega",
    "Austria": "Áustria",
    "Jordan": "Jordânia",
    "Portugal": "Portugal",
    "England": "Inglaterra",
    "Croatia": "Croácia",
    "Ghana": "Gana",
    "Panama": "Panamá",
    "Uzbekistan": "Uzbequistão",
    "Colombia": "Colômbia",
    "Paraguay": "Paraguai",
    "Curaçao": "Curaçao",
    "Curacao": "Curaçao",
    "Bosnia-Herzegovina": "Bósnia e Herzegovina",
    "Bosnia and Herzegovina": "Bósnia e Herzegovina",
    "Bosnia & Herzegovina": "Bósnia e Herzegovina",
    "Serbia": "Sérvia",
    "Kosovo": "Kosovo",
    "Venezuela": "Venezuela",
    "Honduras": "Honduras",
    "El Salvador": "El Salvador",
    "Jamaica": "Jamaica",
    "Trinidad and Tobago": "Trinidad e Tobago",
    "Cuba": "Cuba",
    "Bahrain": "Barein",
    "Iraq": "Iraque",
    "Kuwait": "Kuwait",
    "Oman": "Omã",
    "Yemen": "Iêmen",
    "Syria": "Síria",
    "Palestine": "Palestina",
    "Lebanon": "Líbano",
    "United Arab Emirates": "Emirados Árabes",
    "Cameroon": "Camarões",
    "Nigeria": "Nigéria",
    "Mali": "Mali",
    "Guinea": "Guiné",
    "Mozambique": "Moçambique",
    "Angola": "Angola",
    "Tanzania": "Tanzânia",
    "Uganda": "Uganda",
    "Kenya": "Quênia",
    "Ethiopia": "Etiópia",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbabwe",
    "Namibia": "Namíbia",
    "Botswana": "Botsuana",
    "Rwanda": "Ruanda",
    "Sudan": "Sudão",
    "Libya": "Líbia",
    "DR Congo": "RD Congo",
    "Congo DR": "RD Congo",
    "Democratic Republic of Congo": "RD Congo",
    "Democratic Republic of the Congo": "RD Congo",
    "Congo": "Congo",
    "Togo": "Togo",
    "Benin": "Benim",
    "Burkina Faso": "Burkina Faso",
    "Gambia": "Gâmbia",
    "Sierra Leone": "Serra Leoa",
    "Liberia": "Libéria",
    "Guinea-Bissau": "Guiné-Bissau",
    "Comoros": "Comores",
    "Mauritania": "Mauritânia",
    "Niger": "Níger",
    "Chad": "Chade",
    "Central African Republic": "República Centro-Africana",
    "Eritrea": "Eritreia",
    "Somalia": "Somália",
    "Djibouti": "Djibuti",
    "Lesotho": "Lesoto",
    "Eswatini": "Eswatini",
    "Thailand": "Tailândia",
    "Vietnam": "Vietnã",
    "Indonesia": "Indonésia",
    "Malaysia": "Malásia",
    "Philippines": "Filipinas",
    "China PR": "China",
    "China": "China",
    "India": "Índia",
    "Pakistan": "Paquistão",
    "Bangladesh": "Bangladesh",
    "Myanmar": "Mianmar",
    "Cambodia": "Camboja",
    "Laos": "Laos",
    "Singapore": "Singapura",
    "Tajikistan": "Tajiquistão",
    "Kyrgyzstan": "Quirguistão",
    "Turkmenistan": "Turcomenistão",
    "Kazakhstan": "Cazaquistão",
    "Afghanistan": "Afeganistão",
    "Nepal": "Nepal",
    "Sri Lanka": "Sri Lanka",
    "Maldives": "Maldivas",
    "Mongolia": "Mongólia",
    "Hong Kong": "Hong Kong",
    "Macau": "Macau",
    "Taiwan": "Taiwan",
    "North Korea": "Coreia do Norte",
    "Denmark": "Dinamarca",
    "Sweden": "Suécia",
    "Finland": "Finlândia",
    "Poland": "Polônia",
    "Czech Republic": "República Tcheca",
    "Czechia": "República Tcheca",
    "Slovakia": "Eslováquia",
    "Hungary": "Hungria",
    "Romania": "Romênia",
    "Bulgaria": "Bulgária",
    "Greece": "Grécia",
    "Turkey": "Turquia",
    "Türkiye": "Turquia",
    "Ukraine": "Ucrânia",
    "Russia": "Rússia",
    "Belarus": "Bielorrússia",
    "Moldova": "Moldávia",
    "Albania": "Albânia",
    "North Macedonia": "Macedônia do Norte",
    "Slovenia": "Eslovênia",
    "Montenegro": "Montenegro",
    "Cyprus": "Chipre",
    "Malta": "Malta",
    "Luxembourg": "Luxemburgo",
    "Italy": "Itália",
    "Israel": "Israel",
    "Iceland": "Islândia",
    "Ireland": "Irlanda",
    "Wales": "País de Gales",
    "Northern Ireland": "Irlanda do Norte",
    "Faroe Islands": "Ilhas Faroe",
    "Lithuania": "Lituânia",
    "Latvia": "Letônia",
    "Estonia": "Estônia",
    "Georgia": "Geórgia",
    "Armenia": "Armênia",
    "Azerbaijan": "Azerbaijão",
    "Chile": "Chile",
    "Peru": "Peru",
    "Bolivia": "Bolívia",
    "Guyana": "Guiana",
    "Suriname": "Suriname",
    "Costa Rica": "Costa Rica",
    "Guatemala": "Guatemala",
    "Belize": "Belize",
    "Nicaragua": "Nicarágua",
    "Dominican Republic": "República Dominicana",
    "New Caledonia": "Nova Caledônia",
    "Fiji": "Fiji",
    "Papua New Guinea": "Papua Nova Guiné",
    "Solomon Islands": "Ilhas Salomão",
    "Vanuatu": "Vanuatu",
    "Tahiti": "Taiti",
}
